# Generated by Django 5.2 on 2025-04-18 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0002_scan_scan_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scan',
            old_name='target_url',
            new_name='target',
        ),
    ]
