# Generated by Django 5.2 on 2025-04-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0003_rename_target_url_scan_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='vuln_critical',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='vuln_high',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='vuln_info',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='vuln_low',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scan',
            name='vuln_medium',
            field=models.IntegerField(default=0),
        ),
    ]
